class_mem_non_virtual:class_mem_non_virtual.cpp class_mem_with_virtual
	g++ -o class_mem_non_virtual class_mem_non_virtual.cpp
class_mem_with_virtual:class_mem_with_virtual.cpp
	g++ -o class_mem_with_virtual class_mem_with_virtual.cpp
.PHONY:clean
clean:
	rm -f class_mem_non_virtual class_mem_with_virtual
